export const data = [
  {
    id: "1",
    name: "Spain",
    flag: "https://img.uefa.com/imgml/flags/240x240/ESP.png",
    match_played: "7",
    match_won: "7",
    match_drawn: "0",
    match_lost: "0",
    goals: "15",
    goal_conceded: "4",
    possession: "58.15%",
    passing_accuracy: "90.14%",
    balls_recovered: "290",
    tackles_won: "36",
    clean_sheet: "3",
    saves: "18",
    distance_covered: "832.65",
    yellow_card: "16",
    red_card: "1",
  },
  {
    id: "2",
    name: "England",
    flag: "https://img.uefa.com/imgml/flags/240x240/ENG.png",
    match_played: "7",
    match_won: "3",
    match_drawn: "3",
    match_lost: "1",
    goals: "8",
    goal_conceded: "6",
    possession: "55.72%",
    passing_accuracy: "89%",
    balls_recovered: "252",
    tackles_won: "38",
    clean_sheet: "2",
    saves: "17",
    distance_covered: "846.06",
    yellow_card: "14",
    red_card: "0",
  },

  {
    id: "3",
    name: "France",
    flag: "https://img.uefa.com/imgml/flags/240x240/FRA.png",
    match_played: "6",
    match_won: "2",
    match_drawn: "3",
    match_lost: "1",
    goals: "4",
    goal_conceded: "3",
    possession: "49%",
    passing_accuracy: "89.84%",
    balls_recovered: "231",
    tackles_won: "29",
    clean_sheet: "4",
    saves: "16",
    distance_covered: "682.63",
    yellow_card: "9",
    red_card: "0",
  },

  {
    id: "0004",
    name: "Netherlands",
    flag: "https://img.uefa.com/imgml/flags/240x240/NED.png",
    match_played: "6",
    match_won: "3",
    match_drawn: "1",
    match_lost: "2",
    goals: "10",
    goal_conceded: "7",
    possession: "52.67%",
    passing_accuracy: "88.84%",
    balls_recovered: "178",
    tackles_won: "26",
    clean_sheet: "2",
    saves: "18",
    distance_covered: "650.26",
    yellow_card: "11",
    red_card: "0",
  },

  {
    id: "0005",
    name: "Germany",
    flag: "https://img.uefa.com/imgml/flags/240x240/GER.png",
    match_played: "5",
    match_won: "3",
    match_drawn: "1",
    match_lost: "1",
    goals: "11",
    goal_conceded: "4",
    possession: "59.2%",
    passing_accuracy: "91.2%",
    balls_recovered: "211",
    tackles_won: "23",
    clean_sheet: "2",
    saves: "11",
    distance_covered: "610.59",
    yellow_card: "14",
    red_card: "0",
  },

  {
    id: "0006",
    name: "Portugal",
    flag: "https://img.uefa.com/imgml/flags/240x240/POR.png",
    match_played: "5",
    match_won: "2",
    match_drawn: "2",
    match_lost: "1",
    goals: "5",
    goal_conceded: "3",
    possession: "64.8%",
    passing_accuracy: "90.4%",
    balls_recovered: "203",
    tackles_won: "33",
    clean_sheet: "3",
    saves: "11",
    distance_covered: "635.75",
    yellow_card: "10",
    red_card: "0",
  },

  {
    id: "0007",
    name: "Switzerland",
    flag: "https://img.uefa.com/imgml/flags/240x240/SUI.png",
    match_played: "5",
    match_won: "2",
    match_drawn: "3",
    match_lost: "0",
    goals: "8",
    goal_conceded: "4",
    possession: "48.2%",
    passing_accuracy: "86.8%",
    balls_recovered: "177",
    tackles_won: "16",
    clean_sheet: "1",
    saves: "8",
    distance_covered: "597.85",
    yellow_card: "10",
    red_card: "0",
  },

  {
    id: "0008",
    name: "Turkey",
    flag: "https://img.uefa.com/imgml/flags/240x240/TUR.png",
    match_played: "5",
    match_won: "3",
    match_drawn: "0",
    match_lost: "2",
    goals: "8",
    goal_conceded: "8",
    possession: "49%",
    passing_accuracy: "86%",
    balls_recovered: "183",
    tackles_won: "35",
    clean_sheet: "0",
    saves: "16",
    distance_covered: "562.76",
    yellow_card: "20",
    red_card: "1",
  },
  {
    id: "0009",
    name: "Austria",
    flag: "https://img.uefa.com/imgml/flags/240x240/AUS.png",
    match_played: "4",
    match_won: "2",
    match_drawn: "0",
    match_lost: "2",
    goals: "7",
    goal_conceded: "6",
    possession: "53%",
    passing_accuracy: "86%",
    balls_recovered: "179",
    tackles_won: "20",
    clean_sheet: "0",
    saves: "7",
    distance_covered: "462.17",
    yellow_card: "12",
    red_card: "0",
  },

  {
    id: "0010",
    name: "Belgium",
    flag: "https://img.uefa.com/imgml/flags/240x240/BEL.png",
    match_played: "4",
    match_won: "1",
    match_drawn: "1",
    match_lost: "2",
    goals: "2",
    goal_conceded: "2",
    possession: "53.75%",
    passing_accuracy: "87.75%",
    balls_recovered: "130",
    tackles_won: "28",
    clean_sheet: "2",
    saves: "14",
    distance_covered: "439.87",
    yellow_card: "8",
    red_card: "0",
  },
  {
    id: "0011",
    name: "Denmark",
    flag: "https://img.uefa.com/imgml/flags/240x240/DEN.png",
    match_played: "4",
    match_won: "0",
    match_drawn: "3",
    match_lost: "1",
    goals: "2",
    goal_conceded: "4",
    possession: "50.75%",
    passing_accuracy: "86.25%",
    balls_recovered: "171",
    tackles_won: "28",
    clean_sheet: "1",
    saves: "12",
    distance_covered: "451.23",
    yellow_card: "9",
    red_card: "0",
  },
  {
    id: "0012",
    name: "Georgia",
    flag: "https://img.uefa.com/imgml/flags/240x240/GEO.png",
    match_played: "4",
    match_won: "1",
    match_drawn: "1",
    match_lost: "2",
    goals: "5",
    goal_conceded: "8",
    possession: "38.25%",
    passing_accuracy: "81.5%",
    balls_recovered: "169",
    tackles_won: "34",
    clean_sheet: "1",
    saves: "29",
    distance_covered: "448.54",
    yellow_card: "7",
    red_card: "0",
  },

  {
    id: "0013",
    name: "Italy",
    flag: "https://img.uefa.com/imgml/flags/240x240/ITA.png",
    match_played: "4",
    match_won: "1",
    match_drawn: "1",
    match_lost: "2",
    goals: "3",
    goal_conceded: "5",
    possession: "52.5%",
    passing_accuracy: "88.75%",
    balls_recovered: "137",
    tackles_won: "19",
    clean_sheet: "0",
    saves: "14",
    distance_covered: "465.87",
    yellow_card: "10",
    red_card: "0",
  },

  {
    id: "0014",
    name: "Romania",
    flag: "https://img.uefa.com/imgml/flags/240x240/ROM.png",
    match_played: "4",
    match_won: "2",
    match_drawn: "1",
    match_lost: "1",
    goals: "6",
    goal_conceded: "4",
    possession: "50.5%",
    passing_accuracy: "85.25%",
    balls_recovered: "143",
    tackles_won: "21",
    clean_sheet: "1",
    saves: "10",
    distance_covered: "473.12",
    yellow_card: "7",
    red_card: "0",
  },

  {
    id: "0015",
    name: "Slovakia",
    flag: "https://img.uefa.com/imgml/flags/240x240/SVK.png",
    match_played: "4",
    match_won: "2",
    match_drawn: "1",
    match_lost: "1",
    goals: "6",
    goal_conceded: "4",
    possession: "52.25%",
    passing_accuracy: "84.5%",
    balls_recovered: "126",
    tackles_won: "18",
    clean_sheet: "0",
    saves: "12",
    distance_covered: "453.87",
    yellow_card: "10",
    red_card: "0",
  },
  {
    id: "0016",
    name: "Slovenia",
    flag: "https://img.uefa.com/imgml/flags/240x240/SVN.png",
    match_played: "4",
    match_won: "2",
    match_drawn: "1",
    match_lost: "1",
    goals: "5",
    goal_conceded: "3",
    possession: "50%",
    passing_accuracy: "82.5%",
    balls_recovered: "132",
    tackles_won: "22",
    clean_sheet: "1",
    saves: "14",
    distance_covered: "487.91",
    yellow_card: "8",
    red_card: "0",
  },
  {
    id: "0017",
    name: "Albania",
    flag: "https://img.uefa.com/imgml/flags/240x240/ALB.png",
    match_played: "4",
    match_won: "1",
    match_drawn: "1",
    match_lost: "2",
    goals: "3",
    goal_conceded: "6",
    possession: "44.5%",
    passing_accuracy: "80.25%",
    balls_recovered: "148",
    tackles_won: "25",
    clean_sheet: "0",
    saves: "11",
    distance_covered: "459.89",
    yellow_card: "9",
    red_card: "1",
  },

  {
    id: "0018",
    name: "Croatia",
    flag: "https://img.uefa.com/imgml/flags/240x240/CRO.png",
    match_played: "4",
    match_won: "2",
    match_drawn: "1",
    match_lost: "1",
    goals: "7",
    goal_conceded: "5",
    possession: "50.75%",
    passing_accuracy: "85%",
    balls_recovered: "155",
    tackles_won: "29",
    clean_sheet: "1",
    saves: "13",
    distance_covered: "477.65",
    yellow_card: "12",
    red_card: "0",
  },

  {
    id: "0019",
    name: "Czech Republic",
    flag: "https://img.uefa.com/imgml/flags/240x240/CZE.png",
    match_played: "4",
    match_won: "1",
    match_drawn: "2",
    match_lost: "1",
    goals: "4",
    goal_conceded: "4",
    possession: "48%",
    passing_accuracy: "82%",
    balls_recovered: "140",
    tackles_won: "24",
    clean_sheet: "1",
    saves: "10",
    distance_covered: "452.56",
    yellow_card: "8",
    red_card: "0",
  },

  {
    id: "0020",
    name: "Hungary",
    flag: "https://img.uefa.com/imgml/flags/240x240/HUN.png",
    match_played: "4",
    match_won: "2",
    match_drawn: "0",
    match_lost: "2",
    goals: "5",
    goal_conceded: "5",
    possession: "49.5%",
    passing_accuracy: "83%",
    balls_recovered: "133",
    tackles_won: "26",
    clean_sheet: "1",
    saves: "8",
    distance_covered: "471.23",
    yellow_card: "11",
    red_card: "0",
  },

  {
    id: "0021",
    name: "Poland",
    flag: "https://img.uefa.com/imgml/flags/240x240/POL.png",
    match_played: "4",
    match_won: "1",
    match_drawn: "1",
    match_lost: "2",
    goals: "3",
    goal_conceded: "6",
    possession: "46%",
    passing_accuracy: "82%",
    balls_recovered: "140",
    tackles_won: "23",
    clean_sheet: "0",
    saves: "10",
    distance_covered: "455.87",
    yellow_card: "10",
    red_card: "0",
  },
  {
    id: "0022",
    name: "Serbia",
    flag: "https://img.uefa.com/imgml/flags/240x240/SRB.png",
    match_played: "4",
    match_won: "2",
    match_drawn: "1",
    match_lost: "1",
    goals: "6",
    goal_conceded: "4",
    possession: "50%",
    passing_accuracy: "84%",
    balls_recovered: "147",
    tackles_won: "29",
    clean_sheet: "1",
    saves: "12",
    distance_covered: "463.45",
    yellow_card: "8",
    red_card: "1",
  },

  {
    id: "0023",
    name: "Ukraine",
    flag: "https://img.uefa.com/imgml/flags/240x240/UKR.png",
    match_played: "4",
    match_won: "2",
    match_drawn: "1",
    match_lost: "1",
    goals: "5",
    goal_conceded: "3",
    possession: "53%",
    passing_accuracy: "85%",
    balls_recovered: "162",
    tackles_won: "28",
    clean_sheet: "1",
    saves: "15",
    distance_covered: "470.75",
    yellow_card: "9",
    red_card: "0",
  },
];

export const players = [
  {
    id: "1",
    name: "Spain",
    infoplayer: [
      {
        id: "1",
        name: "David Raya",
        age: "28",
        match: "1",
        position: "Goalkeeper",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250171278.png",
      },
      {
        id: "0002",
        name: "Álex Remiro",
        age: "29",
        match: "-",
        position: "Goalkeeper",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250066244.png",
      },
      {
        id: "0003",
        name: "Unai Simón",
        age: "27",
        match: "6",
        position: "Goalkeeper",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250076116.png",
      },
      {
        id: "0004",
        name: "Dani Carvajal",
        age: "32",
        match: "5",
        position: "Defender",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250024448.png",
      },
      {
        id: "0005",
        name: "Robin Le Normand",
        age: "27",
        match: "6",
        position: "Defender",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250112513.png",
      },
      {
        id: "0006",
        name: "Nacho",
        age: "34",
        match: "4",
        position: "Defender",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/1900122.png",
      },
      {
        id: "0007",
        name: "Daniel Vivian",
        age: "25",
        match: "2",
        position: "Defender",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250194503.png",
      },
      {
        id: "0008",
        name: "Alejandro Grimaldo",
        age: "28",
        match: "2",
        position: "Defender",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250042422.png",
      },
      {
        id: "0009",
        name: "Aymeric Laporte",
        age: "30",
        match: "6",
        position: "Defender",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250027046.png",
      },
      {
        id: "0010",
        name: "Marc Cucurella",
        age: "25",
        match: "6",
        position: "Defender",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250076168.png",
      },
      {
        id: "0011",
        name: "Mikel Merino",
        age: "28",
        match: "7",
        position: "Midfielder",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250080572.png",
      },
      {
        id: "0012",
        name: "Fabián Ruiz",
        age: "28",
        match: "6",
        position: "Midfielder",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250115436.png",
      },
      {
        id: "0013",
        name: "Álex Baena",
        age: "22",
        match: "2",
        position: "Midfielder",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250106963.png",
      },
      {
        id: "0014",
        name: "Rodri",
        age: "28",
        match: "6",
        position: "Midfielder",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250082664.png",
      },
      {
        id: "0015",
        name: "Nico Williams",
        age: "22",
        match: "6",
        position: "Midfielder",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250163185.png",
      },
      {
        id: "0016",
        name: "Martin Zubimendi",
        age: "25",
        match: "4",
        position: "Midfielder",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250143679.png",
      },
      {
        id: "0017",
        name: "Pedri",
        age: "21",
        match: "4",
        position: "Midfielder",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250143693.png",
      },
      {
        id: "0018",
        name: "Mikel Oyarzabal",
        age: "27",
        match: "7",
        position: "Midfielder",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250097180.png",
      },
      {
        id: "0019",
        name: "Álvaro Morata",
        age: "31",
        match: "7",
        position: "Forward",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250024456.png",
      },
      {
        id: "0020",
        name: "Joselu",
        age: "34",
        match: "2",
        position: "Forward",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250005193.png",
      },
      {
        id: "0021",
        name: "Dani Olmo",
        age: "26",
        match: "6",
        position: "Forward",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250081720.png",
      },
      {
        id: "0022",
        name: "Ferran Torres",
        age: "24",
        match: "5",
        position: "Forward",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250088320.png",
      },
      {
        id: "0023",
        name: "Lamine Yamal",
        age: "17",
        match: "7",
        position: "Forward",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250176450.png",
      },
      {
        id: "0024",
        name: "Jesús Navas",
        age: "38",
        match: "3",
        position: "Forward",
        image: "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/69173.png",
      },
      {
        id: "0025",
        name: "Fermín López",
        age: "21",
        match: "1",
        position: "Forward",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250164780.png",
      },
      {
        id: "0026",
        name: "Ayoze Pérez",
        age: "30",
        match: "1",
        position: "Forward",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250075625.png",
      },
    ],
  },
  {
    id: "2",
    name: "England",
    infoplayer: [
      {
        name: "Jordan Pickford",
        age: "30",
        match: "7",
        position: "Goalkepper",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250024791.png",
      },

      {
        name: "Aaron Ramsdale",
        age: "26",
        match: "-",
        position: "Goalkepper",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250105912.png",
      },

      {
        name: "Dean Henderson",
        age: "27",
        match: "-",
        position: "Goalkepper",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250064823.png",
      },

      {
        name: "Kyle Walker",
        age: "34",
        match: "7",
        position: "Defender",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250010259.png",
      },

      {
        name: "Luke Shaw",
        age: "29",
        match: "3",
        position: "Defender",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250042705.png",
      },

      {
        name: "John Stones",
        age: "30",
        match: "7",
        position: "Defender",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250064233.png",
      },

      {
        name: "Marc Guéhi",
        age: "24",
        match: "6",
        position: "Defender",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250086928.png",
      },

      {
        name: "Trent Alexander-Arnold",
        age: "25",
        match: "4",
        position: "Defender",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250076357.png",
      },
      {
        name: "Kieran Trippier",
        age: "33",
        match: "6",
        position: "Defender",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250000919.png",
      },

      {
        name: "Ezri Konsa",
        age: "26",
        match: "3",
        position: "Defender",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250123068.png",
      },
      {
        name: "Lewis Dunk",
        age: "32",
        match: "-",
        position: "Defender",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250021043.png",
      },

      {
        name: "Joe Gomez",
        age: "27",
        match: "-",
        position: "Defender",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250058215.png",
      },
      {
        name: "Declan Rice",
        age: "25",
        match: "7",
        position: "Midfielder",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250083732.png",
      },
      {
        name: "Jude Bellingham",
        age: "21",
        match: "7",
        position: "Midfielder",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250128377.png",
      },
      {
        name: "Phil Foden",
        age: "24",
        match: "7",
        position: "Midfielder",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250101534.png",
      },
      {
        name: "Conor Gallagher",
        age: "24",
        match: "5",
        position: "Midfielder",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250113103.png",
      },
      {
        name: "Cole Palmer",
        age: "22",
        match: "5",
        position: "Midfielder",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250124282.png",
      },
      {
        name: "Adam Wharton",
        age: "20",
        match: "-",
        position: "Midfielder",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250178736.png",
      },
      {
        name: "Kobbie Mainoo",
        age: "19",
        match: "6",
        position: "Midfielder",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250165175.png",
      },
      {
        name: "Bukayo Saka",
        age: "22",
        match: "7",
        position: "Forwards",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250106939.png",
      },
      {
        name: "Harry Kane",
        age: "30",
        match: "7",
        position: "Forwards",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250016833.png",
      },
      {
        name: "Ivan Toney",
        age: "28",
        match: "3",
        position: "Forwards",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250178523.png",
      },
      {
        name: "Anthony Gordon",
        age: "23",
        match: "1",
        position: "Forwards",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250117036.png",
      },
      {
        name: "Ollie Watkins",
        age: "28",
        match: "3",
        position: "Forwards",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250150887.png",
      },
      {
        name: "Jarrod Bowen",
        age: "27",
        match: "2",
        position: "Forwards",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250163877.png",
      },
      {
        name: "Eberechi Eze",
        age: "26",
        match: "3",
        position: "Forwards",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250134376.png",
      },
    ],
  },
  {
    id: "3",
    name: "France",
    infoplayer: [
      {
        name: "Brice Samba",
        age: "30",
        match: "-",
        position: "Goalkepper",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250059123.png",
      },

      {
        name: "Mike Maignan",
        age: "29",
        match: "6",
        position: "Goalkepper",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250042780.png",
      },

      {
        name: "Alphonse Areola",
        age: "31",
        match: "-",
        position: "Goalkepper",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250013997.png",
      },

      {
        name: "Benjamin Pavard",
        age: "28",
        match: "-",
        position: "Defender",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250081921.png",
      },

      {
        name: "Ferland Mendy",
        age: "29",
        match: "-",
        position: "Defender",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250112803.png",
      },

      {
        name: "Dayot Upamecano",
        age: "25",
        match: "6",
        position: "Defender",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250079545.png",
      },

      {
        name: "Jules Koundé",
        age: "25",
        match: "6",
        position: "Defender",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250096309.png",
      },

      {
        name: "William Saliba",
        age: "23",
        match: "6",
        position: "Defender",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250127439.png",
      },
      {
        name: "Jonathan Clauss",
        age: "31",
        match: "-",
        position: "Defender",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250171228.png",
      },

      {
        name: "Theo Hernández",
        age: "26",
        match: "6",
        position: "Defender",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250076126.png",
      },
      {
        name: "Ibrahima Konaté",
        age: "25",
        match: "-",
        position: "Defender",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250091013.png",
      },

      {
        name: "Eduardo Camavinga",
        age: "21",
        match: "4",
        position: "Midfielder",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250128270.png",
      },
      {
        name: "Antoine Griezmann",
        age: "33",
        match: "6",
        position: "Midfielder",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250019498.png",
      },
      {
        name: "Aurélien Tchouameni",
        age: "24",
        match: "5",
        position: "Midfielder",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250105244.png",
      },
      {
        name: "N'Golo Kanté",
        age: "33",
        match: "6",
        position: "Midfielder",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250097248.png",
      },
      {
        name: "Adrien Rabiot",
        age: "29",
        match: "5",
        position: "Midfielder",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250053905.png",
      },
      {
        name: "Warren Zaïre-Emery",
        age: "18",
        match: "-",
        position: "Midfielder",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250153849.png",
      },
      {
        name: "Youssouf Fofana",
        age: "25",
        match: "3",
        position: "Midfielder",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250132399.png",
      },
      {
        name: "Olivier Giroud",
        age: "37",
        match: "4",
        position: "Forwards",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250020851.png",
      },
      {
        name: "Kylian Mbappé",
        age: "25",
        match: "5",
        position: "Forwards",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250076574.png",
      },
      {
        name: "Ousmane Dembélé",
        age: "27",
        match: "5",
        position: "Forwards",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250066886.png",
      },
      {
        name: "Randal Kolo Muani",
        age: "25",
        match: "5",
        position: "Forwards",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250146926.png",
      },
      {
        name: "Marcus Thuram",
        age: "26",
        match: "4",
        position: "Forwards",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250068805.png",
      },
      {
        name: "Kingsley Coman",
        age: "28",
        match: "1",
        position: "Forwards",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250054949.png",
      },
      {
        name: "Bradley Barcola",
        age: "21",
        match: "3",
        position: "Forwards",
        image:
          "https://img.uefa.com/imgml/TP/players/3/2024/cutoff/250134138.png",
      },
    ],
  },
];
